server:
  port: 9000



spring:
  datasource:
    url: jdbc:psql://192.168.0.53:5432/user_registration/
    username: root
    password: root22!
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true